version: '2.1'
services:
  mqtt:
    build: .
    depends_on:
      - postgresql
    ports:
      - "1883:1883"
      - "9001:9001"
  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mqtt
      POSTGRES_PASSWORD: sbgW$Y#3r6
      POSTGRES_DB: mqtt
